# Generated by Django 4.0.4 on 2022-07-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cedula', models.CharField(max_length=50, verbose_name='Cédula')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
            ],
        ),
    ]
